/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/bulbasaur.glb -o src/components/bulbasaur.tsx 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Bulbasaur_92CFB0: THREE.Mesh;
    Bulbasaur_FFFFFF: THREE.Mesh;
    Bulbasaur_AD3946: THREE.Mesh;
    Bulbasaur_6BA966: THREE.Mesh;
    Bulbasaur_5C8A66: THREE.Mesh;
  };
  materials: {
    Bulbasaur_92CFB0: THREE.MeshPhysicalMaterial;
    Bulbasaur_FFFFFF: THREE.MeshPhysicalMaterial;
    Bulbasaur_AD3946: THREE.MeshPhysicalMaterial;
    Bulbasaur_6BA966: THREE.MeshPhysicalMaterial;
    Bulbasaur_5C8A66: THREE.MeshPhysicalMaterial;
  };
};

export function Bulbasaur(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/bulbasaur.glb") as GLTFResult;

  // 모든 재질에 대해 기본 PBR 속성 설정
  Object.values(materials).forEach((material) => {
    material.roughness = 0.8;
    material.metalness = 0.2;
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bulbasaur_92CFB0.geometry}
        material={materials.Bulbasaur_92CFB0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bulbasaur_FFFFFF.geometry}
        material={materials.Bulbasaur_FFFFFF}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bulbasaur_AD3946.geometry}
        material={materials.Bulbasaur_AD3946}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bulbasaur_6BA966.geometry}
        material={materials.Bulbasaur_6BA966}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bulbasaur_5C8A66.geometry}
        material={materials.Bulbasaur_5C8A66}
      />
    </group>
  );
}

useGLTF.preload("/models/bulbasaur.glb");
