/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/bulbasaur.glb -o src/components/bulbasaur.tsx 
*/

import * as THREE from "three";
import React, { useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Bulbasaur_Grass: THREE.Mesh;
  };
  materials: {};
};

export function Bulbasaur(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/bulbasaur.glb") as GLTFResult;

  const greenMaterial = new THREE.MeshStandardMaterial({
    color: "#92ceb0",
    roughness: 0.3,
    metalness: 0.8,
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Bulbasaur_Grass.geometry}
        material={greenMaterial}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/bulbasaur.glb");
