/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/charmander.glb -o src/components/charmander.tsx 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Charmander_Fire: THREE.Mesh;
  };
  materials: {};
};

export function Charmander(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/charmander.glb") as GLTFResult;

  const redMaterial = new THREE.MeshStandardMaterial({
    color: "#f26451",
    roughness: 0.3,
    metalness: 0.8,
  });
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Charmander_Fire.geometry}
        material={redMaterial}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/charmander.glb");
