/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/squirtle.glb -o src/components/squirtle.tsx 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Squirtle_Water: THREE.Mesh;
  };
  materials: {};
};

export function Squirtle(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/squirtle.glb") as GLTFResult;

  const blueMaterial = new THREE.MeshStandardMaterial({
    color: "#85cedf",
    roughness: 0.3,
    metalness: 0.8,
  });
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Squirtle_Water.geometry}
        material={blueMaterial}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/squirtle.glb");
